#This palybook used to auto scaling the frontend using frontend.aws_ec2.yaml
- name: install nginx
  hosts: aws_ec2
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start enable 
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes