- name: setup for user
  hosts: user
  become: yes
  tasks: 
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs 
      state: present
  
  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      shell: /sbin/nologin
      home: /app

  - name: delete a directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: removing downloaded file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent
      
  - name: downloading user application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: extracting the file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  
  - name: install dependencies
    community.general.npm:
      path: /app
  
  -  name: user service
     ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: user
      enabled: true
      state: started
      daemon_reload: true

